### ISSUE TITLE
Base58check

### ISSUE THREAD

**Issue by dcousens** [cryptocoinjs/coinstring#6]
Currently there exists https://github.com/cryptocoinjs/coinstring/ and https://github.com/bitcoinjs/bs58check.

In my stack https://github.com/cryptocoinjs/bip38 is the only package that uses coinstring, so I figured I'd ask here:

Can we consolidate this in some way?

I'm open to anything,  however I find the name `coinstring` quite confusing.
I've since moved https://github.com/bitcoinjs/bs58check to the https://github.com/bitcoinjs organization.

@jprichardson thoughts?

**Comment by jprichardson** [comment]
I made this repo when I thought that base 58 check required something about version numbers. This module may be a bit too complicated actually. I can see how `coinstring` may be confusing. Let me think about this a bit.

**Comment by dcousens** [comment]
No worries,  let me know what you think up :+1:

**Comment by dcousens** [comment]
bump @jprichardson

**Comment by jprichardson** [comment]
What do you think is the best course of action?

**Comment by dcousens** [comment]
For me?  The ideal course of action is to deprecate this package and use `bs58check` in BIP38.

**Comment by dcousens** [comment]
@jprichardson thoughts?

**Comment by jprichardson** [comment]
> @jprichardson thoughts?

OK, I'm considering deprecating `coinstring` in favor of `bs58check`. I may also just use `bs58check` as a dependency of `coinstring`...

**Comment by dcousens** [comment]
Did you want to do the PR?

**Comment by jprichardson** [comment]
I'm not sure if the dependency or deprecation makes sense... thoughts? I suppose dependency feels like a good intermediate step.

**Comment by dcousens** [comment]
I think that will make the transition much simpler, definitely.

**Comment by dcousens** [comment]
If you are going with deprecation, shall I close this issue and let you write up the deprecation warning?

**Comment by dcousens** [comment]
ping @jprichardson

**Comment by jprichardson** [comment]
https://github.com/cryptocoinjs/coinstring/commit/bf8f0464d43b9b7b4c8f91760924b705db2cff6c
